#!/usr/bin/env kross
# -*- coding: utf-8 -*-
# Dependings: ktorrent, python, kross, kross-python
# Path: ~/.kde4/share/apps/ktorrent/scripts/ktorrent_tracker_adder.py

ScriptName = "ktorrent_tracker_adder.py"

import KTorrent
import KTScriptingPlugin
import Kross

links=  [
	    "http://77.106.108.90:2710/announce",
	    "http://retracker.nts.su:2710/announce",
	    "http://bt.rutracker.cc/ann",
	    "http://bt2.rutracker.cc/ann",
	    "http://bt3.rutracker.cc/ann",
	    "http://bt4.rutracker.cc/ann",
	    "http://tracker.tfile.me/announce.php",
	    "http://bt.rutor.org:2710/announce",
	    "http://newstudio.tv:2710/announce",
	    "http://bt.nnm-club.info:2710/announce",
	    "http://pubt.net:2710/announce",
	    "http://retracker.211.ru/announce.php",
	    "http://retracker.bashtel.ru/announce.php",
	    "http://rt.orionnet.ru/announce.php",
	    "http://sound-park.ru/announce.php",
	    "http://streamzone.org:2720/announce",
	    "http://torrent.rus.ec:2710/announce",
	    "http://newstudio.tv:2710/00032db57b6c61eae6b4213700562898/announce",
	    "http://tracker.ilibr.org:6969/announce",
	    "http://bt.unionpeer.org:777/announce",
	    "http://bt.cngba.com/announce",
	    "udp://tracker.publicbt.com/announce",
	    "http://tracker.edgebooster.com:6969/announce",
	    "http://i.bandito.org/announce.php?ak=11b2d04bda&",
	    "http://tbp.tracker.prq.to/announce",
	    "http://bt7.tracktor.in/tracker.php/67620d225e3f9efaa93d0f5da04c1ad5/announce",
	    "http://bt.nnm-club.ru:2710/announce",
	    "http://i.bandito.org/announce.php",
	    "http://bt.peerseed.ru/announce",
	    "http://tr5.kinozal.tv/ann?uk=K1beTGyzvx",
	    "http://beeretracker.ru/announce.php",
	    "http://bt.nnm-club.info:2710/announce",
	    "http://bt3.tracktor.in/tracker.php/67620d225e3f9efaa93d0f5da04c1ad5/announce",
	    "http://bt.rutor.org:2710/announce",
	    "http://trackhub.appspot.com/announce",
	    "http://www.torrent.by/announce.php",
	    "http://fullboxtorrent.com/announce",
	    "http://announce.mybits.ws:2710/announce",
	    "http://tracker.multisearch.ru/announce",
	    "udp://tracker.openbittorrent.com/announce",
	    "http://bt.vtracker.org/bt/announce.php?uk=1BJeW6blFA&",
	    "http://84.16.233.232/Tracker/announce.php",
	    "http://bt6.tracktor.in/tracker.php/67620d225e3f9efaa93d0f5da04c1ad5/announce",
	    "http://announce.freeexchange.ru:2710/announce",
	    "http://tracker.bittorrent.am/announce",
	    "http://eztv.tracker.prq.to/announce",
	    "http://www.filebase.ws:5678/announce",
	    "http://retracker3.netbynet.ru/announce.php",
	    "http://psychocydd.co.uk:2710/announce",
	    "http://tracker.yify-torrents.com/announce",
	    "http://torrent-download.to:5869/announce",
	    "http://medbit.ru/announce.php",
	    "http://d-addicts.net:7979/announce",
	    "http://tracker.torrent.to:2710/announce",
	    "http://tracker.megashara.com:2710/announce",
	    "http://24.195.241.41:6969/announce",
	    "http://corbina-local-re-tracker.no-ip.org:2710/announce",
	    "http://freetorrents.org.ua:2710/announce",
	    "http://tracker.harryy.us/announce",
	    "http://torrent.rus.ec:2710/announce",
	    "http://tracker1.torrentino.tv/announce",
	    "http://i.bandito.org/announce.php?uk=aFnt7k16j6&",
	    "http://retracker.spb.ru/announce.php",
	    "udp://tracker.ex.ua/announce",
	    "http://nyaatorrents.info:3277/announce",
	    "http://hg-services2.corbina.net:2710/announce",
	    "http://inferno.demonoid.ph:3389/announce",
	    "http://tracker.zaerc.com/announce.php",
	    "http://torrentphase.com/announce",
	    "http://tpb.tracker.prq.to/announce",
	    "http://bt.firebit.org:2710/announce",
	    "http://torrent.spywareterminator.com:6969/announce",
	    "http://open-tracker.info:6969/announce",
	    "http://announce.opensharing.org:2710/announce",
	    "http://vicky.l-krak.com/announce",

	    "http://tracker.kalkin.de:6969/announce",
	    "http://sgfsdsd.cbnt.info:6968/announce",
	    "http://tr3.kinozal.tv/ann?uk=K1beTGyzvx",
	    "http://conspiracycentral.net:6969/announce",
	    "http://tracker.denness.net/announce",
	    "http://www.h33t.com:3310/announce",
	    "http://t2.pow7.com/announce",
	    "udp://tracker.ipv6tracker.org/announce",
	    "http://sci.phidawn.com:2710/announce",
	    "http://amplicate.appspot.com/announce",
	    "http://tracker.publicbt.com/announce",
	    "http://jonnyfavorite1.appspot.com/announce",
	    "http://10.rarbg.com/announce",
	    "http://bt.svao-ix.ru/announce",
	    "udp://bt.rutor.org:2710",
	    "http://memtracker.appspot.com/announce",
	    "http://bt5.tracktor.in/tracker.php/67620d225e3f9efaa93d0f5da04c1ad5/announce",
	    "http://rt.beeretracker.net/announce.php",
	    "http://www.torrentsnipe.info:2701/announce",
	    "http://i.bandito.org/announce.php?uk=YyxAlb1WPJ&",
	    "http://damntracker.info/announce",
	    "http://torrent.net.pl:3535/announce",
	    "http://94.228.192.98/announce",
	    "http://mirrortorrents.ru:2710/announce",
	    "http://announce.torrentsmd.com/announce",
	    "http://www.filehoster.ru/tracker",
	    "http://exodus.desync.com/announce",
	    "http://tracker.blazing.de/announce",
	    "http://tracker.zone42.ca:6969/announce",
	    "http://mfdsagfdh.wtf.la:6968/announce",
	    "http://tracker.istole.it/announce",
	    "http://denis.stalker.h3q.com/announce",
	    "udp://tracker.openbittorrent.com",
	    "http://pirates.sumotracker.com/announce",
	    "http://dfjsdlf.437000.org.ru:6968/announce",
	    "http://retracker.211.ru/announce.php",
	    "http://www.darkgamex.ch:6969/announce",
	    "http://bt.home-ix.ru/announce.php",
	    "udp://tracker.ccc.de/announce",
	    "http://bt.speedsubs.org:9339/announce",
	    "http://128.195.169.200:328/announce",
	    "udp://bt.rutor.org:2710/announce",
	    "http://piratbit.net/bt/announce.php",
	    "http://ontorrent.net.ru/announce",
	    "http://openbt.my-hit.ru:2710/announce",
	    "udp://tracker.publicbt.com:80",
	    "http://t1.pow7.com/announce",
	    "http://tracker.torrentbox.com:2710/announce",
	    "http://tracker.prq.to:6969/announce",
	    "udp://tracker.ccc.de:80",
	    "http://kaa.animeconnection.net:3389/announce",
	    "http://bt.rutracker.org/ann?uk=A9q2kx7D6K",
	    "http://tracker.xdvdz.com:2710/announce",
	    "udp://tracker.istole.it:80",
	    "http://www.todotorrents.com:2710/announce",
	    "http://bsdfafdg.chickenkiller.com:6968/announce",
	    "http://pow7.com/announce",
	    "http://umunu.com:1984/announce",
	    "http://publicbt.ath.cx/announce",
	    "http://vlv.tv.tracker.prq.to/announce",
	    "http://tracker.frozen-layer.net:6969/announce",
	    "http://nolimits-team.ru/announce",
	    "http://pubt.net:2710/announce",
	    "udp://tracker.istole.it",
	    "http://tracker.prq.to/announceudp://tracker.ipv6tracker.org/announce",
	    "http://torrents4.beeretracker.ru/announce",
	    "http://tracker.bitreactor.to:2710/announce",
	    "http://tracker.tfile.me/announce.php?ak=anonymous!&",
	    "http://tracker.torrentalk.com:2710/announce",
	    "http://bt4.rutracker.org/ann?uk=1gUIGoIs3i",
	    "udp://tracker.openbittorrent.com:80",
	    "http://retracker.local/announce",
	    "http://tracker.torrentparty.com/announce",
	    "http://fr33dom.h33t.com:3310/announce",
	    "http://www.stafverhaegen.be/phpbttrkplus/announce.php",
	    "http://rt.orionnet.ru/announce.php",
	    "http://www.psychocydd.co.uk:2710/announce",
	    "http://bt.svao-ix.ru/announce.php",
	    "udp://open.demonii.com:1337/announce",
	    "udp://bt.rutor.org:2710/announce%20",
	    "http://tracker.token.ro/announce",
	    "http://divxfinal.com/announce.php",
	    "http://9.rarbg.com:2710/announce",
	    "http://wbtt.ath.cx:2710/announce",
	    "http://sound-park.ru/announce.php",
	    "http://tr2.kinozal.tv/announce.php?passkey=6aac5f7508a9076538fddddd7b286141",
	    "http://genesis.1337x.org:1337/announce",
	    "http://tr4.kinozal.tv/ann?uk=K1beTGyzvx",
	    "http://bt5.rutracker.org/ann?uk=fFWN111rad",
	    "http://ipv4.tracker.harry.lu/announce",
	    "http://tracker.nesia.ru/announce",
	    "http://secure.pow7.com/announce",
	    "http://sexxorrents.com/announce",
	    "http://silvengames.ru:2710/announce",
	    "udp://open.demonii.com:1337",
	    "http://bt.rghost.net/announce",
	    "http://bt4.rutracker.org/ann?uk=fFWN111rad",
	    "http://bt2.tracktor.in/tracker.php/67620d225e3f9efaa93d0f5da04c1ad5/announce",
	    "http://share.camoe.cn/announce",
	    "http://vnsaji.015.info:6968/announce",
	    "http://fordred1.appspot.com/announce",
	    "http://z6gw6skubmo2pj43.onion/announce",
	    "http://tracker.0day.kiev.ua/announce.php?passkey=bb59a21a3676d24db8946f06cb85faa6",
	    "http://tracker.sharereactor.ru:2710/announce",
	    "http://bt2.new-team.org:2710/0001766c9e80f83ebf1cd379d697e06f/announce",
	    "udp://tracker.tfile.me/",
	    "http://v6.nyaatorrents.info:3277/announce",
	    "http://www.sumotracker.com/announce",
	    "http://torrent-downloads.to:2710/announce",
	    "http://retracker.kld.ru/announce",
	    "http://sidewinderx.sytes.net:6968/announce",
	    "http://ix3.rutracker.net/announce",
	    "http://file-tracker.net/announce",
	    "http://tfgjhgf.mooo.com:6968/announce",
	    "http://retracker.home/announce",
	    "http://tracker.kamyu.net/announce",
	    "http://tracker.torrentbox.com/announce",
	    "http://nnm-club.ru:2710/announce",
	    "udp://denis.stalker.h3q.com:6969/announce",
	    "http://tracker.coppersurfer.tk:6969/announce",
	    "http://tracker1.publicbt.com/announce",
	    "http://bt.tracktor.in/tracker.php/67620d225e3f9efaa93d0f5da04c1ad5/announce",
	    "http://bt.home-ix.ru/announce",
	    "udp://tracker.tntvillage.scambioetico.org:2710/announce",
	    "http://tracker.tntvillage.scambioetico.org:2710/announce",
	    "http://sdgsd.afz.biz:6968/announce",
	    "http://radioarchive.cc/announce.php",
	    "http://ultraluxx.appspot.com/announce",
	    "http://tracker3.torrentino.com/announce?passkey=00000000000000000000000000000000",
	    "http://brabus.piwko.pl/announce",
	    "http://bt.cngba.com00/announce",
	    "http://btrs-atrack.appspot.com/announce",
	    "http://tracker.concen.cc/announce",
	    "http://exodus.1337x.org/announce",
	    "http://tracker1.torrentum.pl:6969/announce",
	    "http://linuxtracker.org:2710/00000000000000000000000000000000/announce",
	    "http://nemesis.1337x.org/announce",
	    "http://streamzone.org:2720/announce",
	    "http://bt.kinoserver.org:2710/announce",
	    "http://bittorrent.ipnm.ru/announce",
	    "http://torrent.ipnm.ru/announce",
	    "http://tr1.kinozal.tv/ann?uk=K1beTGyzvx",
	    "http://katushek.net:2710/announce",
	    "http://tracker.publicbt.org/announce",
	    "http://www.zen7.ph/track_1/announce.php",
	    "http://torrent.megaseti.ru/announce",
	    "http://tracker.pubt.net:2710/announce",
	    "udp://tracker.istole.it/announce",
	    "http://inferno.demonoid.com:3407/announce",
	    "http://cpleft.com:2710/announce",
	    "http://opentracker.fr333dom.com:6666/announce",
	    "http://freetorrent.ru/announce",
	    "http://free-torrents.org/bt/announce.php?uk=GektNhM46X&",
	    "http://www.progressivetorrents.com/announce.php",
	    "http://torrent-download.to:5869/announce.php",
	    "http://announce.x-torrents.ru:6969/announce",
	    "http://tracker.xpear.de:6969/announce",
	    "http://tracker.prq.to/announce",
	    "http://gdbt.3322.org:6969/announce",
	    "http://opensource.ipnm.ru/announce",
	    "http://look.org.ua:2710/announce",
	    "http://tracker.pornostube.to:6969/announce",
	    "http://tracker2.istole.it:6969/announce",
	    "http://atrack.pow7.com/announce",
	    "http://tracker.torrentbay.to:6969/announce",
	    "http://tracker.anirena.com:81/announce",
	    "http://bt2.rutracker.org/ann?uk=fFWN111rad",
	    "http://nyaatorrents.info:7266/00000000000000000000000000000000/announce",
	    "http://tracker.anime-miako.to:6969/announce",
	    "http://tracker.ipv6tracker.org/announce",
	    "http://tracker.thexfiles.ru/announce",
	    "http://photodiode.mine.nu:6969/announce",
	    "http://retracker.bashtel.ru/announce.php",
	    "http://sombarato.org:6969/announce",
	    "udp://tracker.ccc.de",
	    "udp://tracker.nesia.ru/announce",
	    "http://announce.opensharing.ru:2710/announce",
	    "http://ix.rutracker.net/ann?uk=1gUIGoIs3i",
	    "http://tracker.datorrents.com:6969/announce",
	    "http://denis.stalker.h3q.com:6969/announce",
	    "http://tr0.kinozal.tv/ann?uk=K1beTGyzvx",
	    "http://hfghgfsd.b33r.net:6968/announce",
	    "http://bit-byte.org/announce.php",
	    "http://tracker.boxtorrents.com:2710/announce",
	    "http://announce.xxx-tracker.com:2710/announce",
	    "http://tracker.ilibr.org/announce",
	    "udp://tracker.istole.it:6969",
	    "http://papaja.v2v.cc:6970/announce",
	    "http://re-tracker.ru/announce",
	    "http://freetorrent.ru/announce.php",
	    "http://lsngfsdlgsn.qc.to:6968/announce",
	    "http://tekfu-track.appspot.com/announce",
	    "http://www.rustorka.com:2710/announce",
	    "http://beeretracker.ru/announce",
	    "http://bt2.the9.com:6969/announce",
	    "http://nnbt.org:2710/announce",
	    "http://evolution.tula.su/retracker/announce.php",
	    "http://exodus.desync.com:6969/announceexodus.desync.com:6969/announce",
	    "http://tr2.kinozal.tv/ann?uk=K1beTGyzvx",
	    "http://tracker.rusdivx.ee/announce.php",
	    "http://tracker.ex.ua/announce",
	    "http://share.xdmhy.net00/announce",
	    "http://portal.md/tracker/announce.php",
	    "http://tracko.appspot.com/announce",
	    "http://retracker.netbynet.ru/announce.php",
	    "http://tracker.csze.com/announce",
	    "http://tracker.tfile.me/announce.php?uk=aFnt7k16j6&",
	    "http://t.dattebayo.com:6969/announce",
	    "http://bt3.rutracker.org/ann?uk=Cxg0f10UAt",
	    "http://titor.ru:2710/announce",
	    "http://inferno.demonoid.com:3393/announce",
	    "udp://tracker.publicbt.com",
	    "http://tpb.beeretracker.ru/announce",
	    "http://retracker.spb.ru/announce",
	    "http://tracker.tfile.ru/announce.php?uk=1111111111&",
	    "http://tracker.ccc.de/announce",
	    "http://bt4.tracktor.in/tracker.php/67620d225e3f9efaa93d0f5da04c1ad5/announce",
	    "http://tracker.etree.org:6969/announce",
	    "http://bt.new-team.org:2710/0001766c03fcedd65bf4952901560443/announce",
	    "http://h33t.com/announce",
	    "http://tracker.pow7.com/announce",
	    "http://exodus.desync.com:6969/announce",
	    "http://betadoctor.appspot.com/announce",
	    "http://tracker.0rz.ca/announce",
	    "http://oifnas.aixx.com:6968/announce",
	    "http://photodiode.mine.nu/announce",
	    "http://tracker.irc.su/announce",
	    "http://tracker.openbittorrent.com/announce",
	    "udp://tracker.tfile.ru/",
		  


		  
	]



class KtorrentTrackerAdder:
	def __init__(self):
		KTorrent.log("=========>  Starting ktorrent_tracker_adder.py")
		KTorrent.connect("torrentAdded(const QString &)",self.torrentAdded)

	def torrentAdded(self,info_hash):
		tor = KTorrent.torrent(info_hash)
		tors = KTorrent.torrents()
		KTorrent.log("=========>  torrentAdded=%s,  Priority = %i, " % (tor.name(),tor.priority()))
		trackers = tor.trackers()
		
		for link in links:
		  tor.addTracker(link)
		  tor.setTrackerEnabled(link,1)
		
		tor.setPriority(len(tors))
		KTorrent.orderQueue()

	def unload(self):
		KTorrent.disconnect("torrentAdded(const QString &)",self.torrentAdded)
		KTorrent.log("=========>  Removing ktorrent_tracker_adder.py")

tA = KtorrentTrackerAdder()

def unload():
	global tA
	tA.unload()
	del tA